name: Check Dependencies Diff

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions: {}

jobs:
  check:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - uses: ./.github/actions/setup-java
#      - run: ./gradlew :app-android:assemble --stacktrace
      - uses: ./.github/actions/dependencies-diff
        id: dependencies-diff
        with:
          modules: 'core:common'
          configuration: 'debugRuntimeClasspath'
      - run: echo '${{ steps.dependencies-diff.outputs.exists-diff }}'
