name: Check Dependencies Diff

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions: {}

jobs:
  check:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - uses: ./.github/actions/setup-java
      - uses: ./.github/actions/dependencies-diff
        id: dependencies-diff
        with:
          modules: 'app-android|devDebugRuntimeClasspath core:common core:data core:designsystem core:model core:testing core:ui feature:about feature:contributors feature:floor-map feature:main feature:sessions feature:sponsors feature:staff feature:stamps'
          configuration: 'debugRuntimeClasspath'
      - if: github.event_name == 'pull_request' && steps.dependencies-diff.outputs.exists-diff == 'true'
        uses: marocchino/sticky-pull-request-comment@efaaab3fd41a9c3de579aba759d2552635e590fd # v2.8.0
        with:
          header: dependencies-diff
          number: ${{ github.event.pull_request.number }}
          recreate: true
          message: ':warning: There is a difference in dependencies. See details [here](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}).'
